version: 2

project_name: agent-hub-server

before:
  hooks:
    # Build the embedded frontend before compiling the Go binary.
    # Requires Node.js 20+ and npm to be available in the CI environment.
    - make build-web

builds:
  - id: agent-hub-server
    main: ./cmd/agent-hub-server
    binary: agent-hub-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ["zip"]

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

release:
  draft: false
  prerelease: auto
